// Demo Data with Unsplash Images for RestArtuz Premium UI
import { Category, Product, Banner, MultiLangText } from '../types';

// High-quality Unsplash images for luxury interior design
export const UNSPLASH_IMAGES = {
  // Banners - Large hero images
  banners: [
    'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80', // Luxury interior
    'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80', // Modern kitchen
    'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=1200&q=80', // Marble texture
    'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&q=80', // Living room
  ],
  
  // Categories
  categories: {
    kitchenBacksplash: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    onyx: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    pvcPanel: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
    marble: 'https://images.unsplash.com/photo-1618221381711-42ca8ab6e908?w=800&q=80',
    mirrors: 'https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80',
    glassPartitions: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    stretchCeiling: 'https://images.unsplash.com/photo-1615873968403-89e068629265?w=800&q=80',
    decorativeWall: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80',
    bathroom: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80',
    livingRoom: 'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=800&q=80',
    bedroom: 'https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=800&q=80',
    commercial: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80',
  },
  
  // Products by category
  products: {
    kitchenBacksplash: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80',
      'https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?w=600&q=80',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=600&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80',
    ],
    onyx: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
      'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&q=80',
      'https://images.unsplash.com/photo-1618221381711-42ca8ab6e908?w=600&q=80',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&q=80',
    ],
    pvcPanel: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&q=80',
      'https://images.unsplash.com/photo-1618219740975-d40978bb7378?w=600&q=80',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=600&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&q=80',
    ],
    marble: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&q=80',
      'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&q=80',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80',
    ],
  },
};

// Demo Banners for Home Screen
export const DEMO_BANNERS: Banner[] = [
  {
    id: 'banner-1',
    imageUrl: UNSPLASH_IMAGES.banners[0],
    title: {
      uz: 'Premium Interyer Materiallari',
      ru: 'Премиум Материалы для Интерьера',
      en: 'Premium Interior Materials',
    },
    subtitle: {
      uz: 'Uyingiz uchun eng yaxshi tanlov',
      ru: 'Лучший выбор для вашего дома',
      en: 'The Best Choice for Your Home',
    },
    linkType: 'category',
    linkId: 'cat-1',
    order: 1,
    isActive: true,
  },
  {
    id: 'banner-2',
    imageUrl: UNSPLASH_IMAGES.banners[1],
    title: {
      uz: 'Yangi Kolleksiya 2025',
      ru: 'Новая Коллекция 2025',
      en: 'New Collection 2025',
    },
    subtitle: {
      uz: 'Zamonaviy dizayn tendensiyalari',
      ru: 'Современные тренды дизайна',
      en: 'Modern Design Trends',
    },
    linkType: 'category',
    linkId: 'cat-2',
    order: 2,
    isActive: true,
  },
  {
    id: 'banner-3',
    imageUrl: UNSPLASH_IMAGES.banners[2],
    title: {
      uz: 'Tabiiy Tosh Kolleksiyasi',
      ru: 'Коллекция Натурального Камня',
      en: 'Natural Stone Collection',
    },
    subtitle: {
      uz: 'Onikis va marmar materiallari',
      ru: 'Материалы из оникса и мрамора',
      en: 'Onyx & Marble Materials',
    },
    linkType: 'category',
    linkId: 'cat-3',
    order: 3,
    isActive: true,
  },
];

// Demo Categories
export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: {
      uz: 'Oshxona Artini',
      ru: 'Кухонный Фартук',
      en: 'Kitchen Backsplash',
    },
    description: {
      uz: 'Zamonaviy oshxona artinlari',
      ru: 'Современные кухонные фартуки',
      en: 'Modern kitchen backsplash panels',
    },
    imageUrl: UNSPLASH_IMAGES.categories.kitchenBacksplash,
    order: 1,
    isActive: true,
    productCount: 128,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-2',
    name: {
      uz: 'Onikis Tekstura',
      ru: 'Оникс Текстура',
      en: 'Onyx Texture',
    },
    description: {
      uz: 'Tabiiy onikis panellari',
      ru: 'Натуральные ониксовые панели',
      en: 'Natural onyx stone panels',
    },
    imageUrl: UNSPLASH_IMAGES.categories.onyx,
    order: 2,
    isActive: true,
    productCount: 86,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-3',
    name: {
      uz: 'PVX Panellar',
      ru: 'ПВХ Панели',
      en: 'PVC Panels',
    },
    description: {
      uz: 'Yuqori sifatli PVX panellar',
      ru: 'Высококачественные ПВХ панели',
      en: 'High-quality PVC wall panels',
    },
    imageUrl: UNSPLASH_IMAGES.categories.pvcPanel,
    order: 3,
    isActive: true,
    productCount: 215,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-4',
    name: {
      uz: 'Marmar',
      ru: 'Мрамор',
      en: 'Marble',
    },
    description: {
      uz: 'Premium marmar kolleksiyasi',
      ru: 'Премиум коллекция мрамора',
      en: 'Premium marble collection',
    },
    imageUrl: UNSPLASH_IMAGES.categories.marble,
    order: 4,
    isActive: true,
    productCount: 94,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-5',
    name: {
      uz: 'Oynalar',
      ru: 'Зеркала',
      en: 'Mirrors',
    },
    description: {
      uz: 'Dekorativ oyna panellari',
      ru: 'Декоративные зеркальные панели',
      en: 'Decorative mirror panels',
    },
    imageUrl: UNSPLASH_IMAGES.categories.mirrors,
    order: 5,
    isActive: true,
    productCount: 67,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-6',
    name: {
      uz: 'Shisha Partitsiyalar',
      ru: 'Стеклянные Перегородки',
      en: 'Glass Partitions',
    },
    description: {
      uz: 'Zamonaviy shisha partitsiyalar',
      ru: 'Современные стеклянные перегородки',
      en: 'Modern glass partition systems',
    },
    imageUrl: UNSPLASH_IMAGES.categories.glassPartitions,
    order: 6,
    isActive: true,
    productCount: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-7',
    name: {
      uz: 'Cho\'zilgan Shiftlar',
      ru: 'Натяжные Потолки',
      en: 'Stretch Ceilings',
    },
    description: {
      uz: 'Premium shift yechimlari',
      ru: 'Премиум потолочные решения',
      en: 'Premium ceiling solutions',
    },
    imageUrl: UNSPLASH_IMAGES.categories.stretchCeiling,
    order: 7,
    isActive: true,
    productCount: 78,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-8',
    name: {
      uz: 'Devoriy Panellar',
      ru: 'Декоративные Панели',
      en: 'Decorative Panels',
    },
    description: {
      uz: 'Premium devor bezaklari',
      ru: 'Премиум декор для стен',
      en: 'Premium wall decoration panels',
    },
    imageUrl: UNSPLASH_IMAGES.categories.decorativeWall,
    order: 8,
    isActive: true,
    productCount: 156,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Demo Products
export const DEMO_PRODUCTS: Product[] = [
  // Kitchen Backsplash products
  {
    id: 'prod-1',
    code: 'KB-001',
    name: {
      uz: 'Premium Oq Marmar Artin',
      ru: 'Премиум Белый Мраморный Фартук',
      en: 'Premium White Marble Backsplash',
    },
    categoryId: 'cat-1',
    description: {
      uz: 'Klassik oq marmar ko\'rinishidagi premium oshxona artini',
      ru: 'Премиум кухонный фартук с классическим видом белого мрамора',
      en: 'Premium kitchen backsplash with classic white marble appearance',
    },
    images: [{
      id: 'img-1',
      url: UNSPLASH_IMAGES.products.kitchenBacksplash[0],
      thumbnailUrl: UNSPLASH_IMAGES.products.kitchenBacksplash[0],
      order: 1,
      storagePath: '',
    }],
    thumbnailUrl: UNSPLASH_IMAGES.products.kitchenBacksplash[0],
    material: { uz: 'Shisha', ru: 'Стекло', en: 'Tempered Glass' },
    size: '60x300 cm',
    thickness: '6mm',
    colors: ['White', 'Grey Veins'],
    tags: ['kitchen', 'marble', 'white', 'premium'],
    stockStatus: 'in_stock',
    relatedProductIds: ['prod-2', 'prod-3'],
    viewCount: 1250,
    favoriteCount: 89,
    shareCount: 45,
    isActive: true,
    isFeatured: true,
    isNew: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-2',
    code: 'KB-002',
    name: {
      uz: 'Qora Onikis Artin',
      ru: 'Чёрный Оникс Фартук',
      en: 'Black Onyx Backsplash',
    },
    categoryId: 'cat-1',
    description: {
      uz: 'Hashamatli qora onikis ko\'rinishidagi oshxona artini',
      ru: 'Роскошный кухонный фартук с видом чёрного оникса',
      en: 'Luxurious kitchen backsplash with black onyx appearance',
    },
    images: [{
      id: 'img-2',
      url: UNSPLASH_IMAGES.products.kitchenBacksplash[1],
      thumbnailUrl: UNSPLASH_IMAGES.products.kitchenBacksplash[1],
      order: 1,
      storagePath: '',
    }],
    thumbnailUrl: UNSPLASH_IMAGES.products.kitchenBacksplash[1],
    material: { uz: 'Shisha', ru: 'Стекло', en: 'Tempered Glass' },
    size: '60x300 cm',
    thickness: '6mm',
    colors: ['Black', 'Gold Veins'],
    tags: ['kitchen', 'onyx', 'black', 'luxury'],
    stockStatus: 'in_stock',
    relatedProductIds: ['prod-1', 'prod-3'],
    viewCount: 980,
    favoriteCount: 76,
    shareCount: 32,
    isActive: true,
    isFeatured: true,
    isNew: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Onyx products
  {
    id: 'prod-3',
    code: 'ONX-001',
    name: {
      uz: 'Yashil Onikis Panel',
      ru: 'Зелёный Оникс Панель',
      en: 'Green Onyx Panel',
    },
    categoryId: 'cat-2',
    description: {
      uz: 'Tabiiy yashil onikis tosh paneli LED yoritish bilan',
      ru: 'Натуральная панель из зелёного оникса с LED подсветкой',
      en: 'Natural green onyx stone panel with LED backlighting',
    },
    images: [{
      id: 'img-3',
      url: UNSPLASH_IMAGES.products.onyx[0],
      thumbnailUrl: UNSPLASH_IMAGES.products.onyx[0],
      order: 1,
      storagePath: '',
    }],
    thumbnailUrl: UNSPLASH_IMAGES.products.onyx[0],
    material: { uz: 'Tabiiy Onikis', ru: 'Натуральный Оникс', en: 'Natural Onyx Stone' },
    size: '120x60 cm',
    thickness: '20mm',
    colors: ['Green', 'White Veins'],
    tags: ['onyx', 'green', 'natural', 'backlit'],
    price: 850,
    currency: 'USD',
    stockStatus: 'in_stock',
    relatedProductIds: ['prod-4'],
    viewCount: 2100,
    favoriteCount: 156,
    shareCount: 89,
    isActive: true,
    isFeatured: true,
    isNew: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-4',
    code: 'ONX-002',
    name: {
      uz: 'Asal Onikis Panel',
      ru: 'Медовый Оникс Панель',
      en: 'Honey Onyx Panel',
    },
    categoryId: 'cat-2',
    description: {
      uz: 'Issiq asal rangli onikis panel',
      ru: 'Тёплая медовая ониксовая панель',
      en: 'Warm honey-colored onyx panel',
    },
    images: [{
      id: 'img-4',
      url: UNSPLASH_IMAGES.products.onyx[1],
      thumbnailUrl: UNSPLASH_IMAGES.products.onyx[1],
      order: 1,
      storagePath: '',
    }],
    thumbnailUrl: UNSPLASH_IMAGES.products.onyx[1],
    material: { uz: 'Tabiiy Onikis', ru: 'Натуральный Оникс', en: 'Natural Onyx Stone' },
    size: '100x50 cm',
    thickness: '15mm',
    colors: ['Honey', 'Amber'],
    tags: ['onyx', 'honey', 'warm', 'elegant'],
    price: 720,
    currency: 'USD',
    stockStatus: 'in_stock',
    relatedProductIds: ['prod-3'],
    viewCount: 1560,
    favoriteCount: 98,
    shareCount: 54,
    isActive: true,
    isFeatured: false,
    isNew: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // PVC Panels
  {
    id: 'prod-5',
    code: 'PVC-001',
    name: {
      uz: '3D Geometrik PVX Panel',
      ru: '3D Геометрическая ПВХ Панель',
      en: '3D Geometric PVC Panel',
    },
    categoryId: 'cat-3',
    description: {
      uz: 'Zamonaviy 3D geometrik dizaynli PVX panel',
      ru: 'Современная ПВХ панель с 3D геометрическим дизайном',
      en: 'Modern PVC panel with 3D geometric design',
    },
    images: [{
      id: 'img-5',
      url: UNSPLASH_IMAGES.products.pvcPanel[0],
      thumbnailUrl: UNSPLASH_IMAGES.products.pvcPanel[0],
      order: 1,
      storagePath: '',
    }],
    thumbnailUrl: UNSPLASH_IMAGES.products.pvcPanel[0],
    material: { uz: 'PVX', ru: 'ПВХ', en: 'Premium PVC' },
    size: '50x50 cm',
    thickness: '3mm',
    colors: ['White', 'Available in Custom Colors'],
    tags: ['pvc', '3d', 'geometric', 'modern'],
    stockStatus: 'in_stock',
    relatedProductIds: ['prod-6'],
    viewCount: 890,
    favoriteCount: 67,
    shareCount: 28,
    isActive: true,
    isFeatured: true,
    isNew: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-6',
    code: 'PVC-002',
    name: {
      uz: 'To\'lqinli PVX Panel',
      ru: 'Волнистая ПВХ Панель',
      en: 'Wave Pattern PVC Panel',
    },
    categoryId: 'cat-3',
    description: {
      uz: 'Elegant to\'lqin naqshli devoriy panel',
      ru: 'Элегантная настенная панель с волнистым узором',
      en: 'Elegant wave pattern wall panel',
    },
    images: [{
      id: 'img-6',
      url: UNSPLASH_IMAGES.products.pvcPanel[1],
      thumbnailUrl: UNSPLASH_IMAGES.products.pvcPanel[1],
      order: 1,
      storagePath: '',
    }],
    thumbnailUrl: UNSPLASH_IMAGES.products.pvcPanel[1],
    material: { uz: 'PVX', ru: 'ПВХ', en: 'Premium PVC' },
    size: '60x60 cm',
    thickness: '4mm',
    colors: ['White', 'Cream'],
    tags: ['pvc', 'wave', 'elegant', 'wall'],
    stockStatus: 'in_stock',
    relatedProductIds: ['prod-5'],
    viewCount: 720,
    favoriteCount: 45,
    shareCount: 19,
    isActive: true,
    isFeatured: false,
    isNew: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Marble
  {
    id: 'prod-7',
    code: 'MRB-001',
    name: {
      uz: 'Calacatta Oltin Marmar',
      ru: 'Калакатта Золотой Мрамор',
      en: 'Calacatta Gold Marble',
    },
    categoryId: 'cat-4',
    description: {
      uz: 'Italiyadan keltirilgan premium Calacatta marmar',
      ru: 'Премиум мрамор Калакатта из Италии',
      en: 'Premium Calacatta marble imported from Italy',
    },
    images: [{
      id: 'img-7',
      url: UNSPLASH_IMAGES.products.marble[0],
      thumbnailUrl: UNSPLASH_IMAGES.products.marble[0],
      order: 1,
      storagePath: '',
    }],
    thumbnailUrl: UNSPLASH_IMAGES.products.marble[0],
    material: { uz: 'Tabiiy Marmar', ru: 'Натуральный Мрамор', en: 'Natural Italian Marble' },
    size: '120x60 cm',
    thickness: '20mm',
    colors: ['White', 'Gold Veins'],
    tags: ['marble', 'calacatta', 'italian', 'luxury'],
    price: 1200,
    currency: 'USD',
    stockStatus: 'in_stock',
    relatedProductIds: ['prod-8'],
    viewCount: 3200,
    favoriteCount: 234,
    shareCount: 156,
    isActive: true,
    isFeatured: true,
    isNew: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-8',
    code: 'MRB-002',
    name: {
      uz: 'Nero Marquina Marmar',
      ru: 'Неро Маркина Мрамор',
      en: 'Nero Marquina Marble',
    },
    categoryId: 'cat-4',
    description: {
      uz: 'Ispaniyadan keltirilgan qora marmar',
      ru: 'Чёрный мрамор из Испании',
      en: 'Black marble imported from Spain',
    },
    images: [{
      id: 'img-8',
      url: UNSPLASH_IMAGES.products.marble[1],
      thumbnailUrl: UNSPLASH_IMAGES.products.marble[1],
      order: 1,
      storagePath: '',
    }],
    thumbnailUrl: UNSPLASH_IMAGES.products.marble[1],
    material: { uz: 'Tabiiy Marmar', ru: 'Натуральный Мрамор', en: 'Natural Spanish Marble' },
    size: '120x60 cm',
    thickness: '20mm',
    colors: ['Black', 'White Veins'],
    tags: ['marble', 'nero', 'spanish', 'dramatic'],
    price: 980,
    currency: 'USD',
    stockStatus: 'in_stock',
    relatedProductIds: ['prod-7'],
    viewCount: 2800,
    favoriteCount: 189,
    shareCount: 98,
    isActive: true,
    isFeatured: true,
    isNew: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Featured Collections for Home Screen
export const FEATURED_COLLECTIONS = [
  {
    id: 'collection-1',
    title: {
      uz: 'Oshxona Yechimlari',
      ru: 'Кухонные Решения',
      en: 'Kitchen Solutions',
    },
    description: {
      uz: 'Premium oshxona dizayni',
      ru: 'Премиум дизайн кухни',
      en: 'Premium kitchen design',
    },
    imageUrl: UNSPLASH_IMAGES.categories.kitchenBacksplash,
    categoryId: 'cat-1',
    productCount: 128,
  },
  {
    id: 'collection-2',
    title: {
      uz: 'Tabiiy Toshlar',
      ru: 'Натуральные Камни',
      en: 'Natural Stones',
    },
    description: {
      uz: 'Onikis va marmar',
      ru: 'Оникс и мрамор',
      en: 'Onyx & Marble',
    },
    imageUrl: UNSPLASH_IMAGES.categories.onyx,
    categoryId: 'cat-2',
    productCount: 180,
  },
  {
    id: 'collection-3',
    title: {
      uz: 'Devoriy Bezaklar',
      ru: 'Декор Стен',
      en: 'Wall Decor',
    },
    description: {
      uz: '3D panellar va dekorlar',
      ru: '3D панели и декор',
      en: '3D panels & decor',
    },
    imageUrl: UNSPLASH_IMAGES.categories.decorativeWall,
    categoryId: 'cat-8',
    productCount: 156,
  },
];
